name: TVHeadend
version: 2.0.2-alpha
slug: tvheadend
description: TV streaming server and recorder.
url: 'https://github.com/marious1985/addon-tvheadend'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
webui: 'http://[HOST]:[PORT:9981]/'
#full_access: true
#privileged:
#  - SYS_ADMIN
#  - SYS_RAWIO
#  - SYS_RESOURCE
#  - SYS_MODULE
devices:
   - /dev/dvb/adapter0/demux0
   - /dev/dvb/adapter0/dvr0
   - /dev/dvb/adapter0/frontend0
   - /dev/dvb/adapter0/net0
   - /dev/dvb/adapter1/demux0
   - /dev/dvb/adapter1/dvr0
   - /dev/dvb/adapter1/frontend0
   - /dev/dvb/adapter1/net0

ports:
  9981/tcp: 9981
  9982/tcp: 9982
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
map:
  - 'config:rw'
options:
  system_packages: []
  init_commands: []
schema:
  system_packages:
    - str
  init_commands:
    - str
image: 'ghcr.io/marious1985/tvheadend/{arch}'
